In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np #alias shortform
print(np.__version__)

1.24.3


In [3]:
print("hello welcome in jupyter notebook")

hello welcome in jupyter notebook


In [4]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(type(arr)) # datatype 
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [7]:
import numpy
tup = (1,2,3,4,5)
print(type(tup))
    
arr = numpy.array(tup)
print(type(tup))
print(type(arr)) # datatype 
print(arr)

<class 'tuple'>
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [1]:
import numpy
lis = [1,2,3,4,5]
arr = numpy.array(lis)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [2]:
lis = [10, 'ab', "python", 12.4] #update the lis element...

In [ ]:
tup = (10, 'ab', 'python', 12.4)

In [4]:
#zero dimentioanl
import numpy
arr = numpy.array(5)
print(type(arr))
print(arr)
print(arr.ndim)

<class 'numpy.ndarray'>
5
0


In [6]:
#one-dimentaional..
import numpy
arr = numpy.array([10,20,30,40])
print(arr)
print(arr.ndim)

[10 20 30 40]
1


In [15]:
import numpy
arr = numpy.array([[1,2,3,4,5],[10,20,30,40,50]])
print(arr)
print("dimention of array", arr.ndim)
print("shape of array",arr.shape)
print("size of array", arr.size)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
dimention of array 2
shape of array (2, 5)
size of array 10


In [ ]:
2 by 5 ---- two by five...

In [16]:
import numpy as np
a = np.array(42) #zero-dim
b = np.array([1, 2, 3, 4, 5]) #one-dim
c = np.array([[1, 2, 3], [4, 5, 6]]) #two-dim
print(a)
print(b)
print(c)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [25]:
import numpy as np

arr = np.array([10, 20, 35, 40])

print(arr[0:3])
#index position
#index position + addition
# slicing...

[10 20 35]


In [12]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('element is: ', arr[1, 4]) #arr[row, col]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
element is:  10


In [17]:
import numpy as np

arr = np.array([  [1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]   ])
print(arr)
print('value:-------- ', arr[0, 0]) # 0 is row...& 1 column...
print('value:-------- ', arr[0, 1])
print('value:-------- ', arr[0, 2])
print('value:-------- ', arr[0, 3])
print('value:-------- ', arr[0, 4])
print(arr.ndim)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
value:--------  1
value:--------  2
value:--------  3
value:--------  4
value:--------  5
2
(3, 5)


In [25]:
# two dim array
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[1, 1:4])
#row level slicing
#coloum level slicing..

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [30]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11,12,13,14,15]])
print(arr)
print(arr[0:3, 1:4]) # row level slicing & column level slicing


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
